/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TokenVestingInterface extends Interface {
    getFunction(nameOrSignature: "beneficiary" | "claim" | "cliffDuration" | "duration" | "fund" | "funded" | "getClaimableAmount" | "getVestedAmount" | "owner" | "partialClaim" | "released" | "start" | "token" | "totalAllocation"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'beneficiary', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'cliffDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'duration', values?: undefined): string;
encodeFunctionData(functionFragment: 'fund', values?: undefined): string;
encodeFunctionData(functionFragment: 'funded', values?: undefined): string;
encodeFunctionData(functionFragment: 'getClaimableAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVestedAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'partialClaim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'released', values?: undefined): string;
encodeFunctionData(functionFragment: 'start', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAllocation', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'beneficiary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cliffDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'duration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'funded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaimableAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVestedAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'partialClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'released', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'start', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAllocation', data: BytesLike): Result;
  }

  

  export interface TokenVesting extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenVesting;
    waitForDeployment(): Promise<this>;

    interface: TokenVestingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    beneficiary: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    cliffDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    duration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    funded: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getClaimableAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVestedAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    partialClaim: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    released: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    start: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAllocation: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'beneficiary'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cliffDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'duration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'funded'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getClaimableAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVestedAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'partialClaim'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'released'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'start'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAllocation'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }